# Phylogenetic Effects {#phylogenetic}
```{r, echo=FALSE, message=FALSE,warning=FALSE}
rm(list=ls())
library(dplyr)
library(flair)
library(lme4)
library(MCMCglmm)
library(scales)
library(squidSim)
library(knitr)
set.seed(25)
```
## Brownian motion


```{r}
library(ape)
library(squidSim)
data(bird.families)

squid_dat <- simulate_population(
	data_structure=data.frame(taxon=bird.families$tip.label),
	parameters=list(
		taxon=list(
			vcov=1
		),
		residual=list(
			vcov=1
		)
	),
	phylogeny=list(taxon=bird.families)
)

pop_dat <- get_population_data(squid_dat)
var(pop_dat$taxon_effect)
var(pop_dat$y)

phylo_vcv <- ape::vcv(bird.families, corr = TRUE)
cv <- chol(phylo_vcv)
#methods::as(cv, "dgCMatrix")

cc<-replicate(200,{
e <- rnorm(n=nrow(cv), 0, sqrt(0.5))
y <- rnorm(n=nrow(cv), 0, sqrt(0.5))
y <- methods::as(Matrix::crossprod(cv,y),"matrix")
dat_y <- data.frame(y=y[,1]+e,taxon=rownames(y))
model3<-MCMCglmm(y~1, 
	random=~taxon, 
	ginverse=list(taxon=Ainv),
	data=dat_y, 
	prior=prior, 
	verbose=FALSE, nitt=13000, burnin=3000, thin=10)
summary(model3)

e <- rnorm(n=nrow(cv), 0, sqrt(0.5))
x <- MCMCglmm::rbv(bird.families,0.5,nodes="TIPS")
dat_x <- data.frame(y=x[,1]+e,taxon=rownames(x))

model2<-MCMCglmm(y~1, 
	random=~taxon, 
	ginverse=list(taxon=Ainv),
	data=dat_x, 
	prior=prior, 
	verbose=FALSE, nitt=13000, burnin=3000, thin=10)

c(summary(model2)$Gcov[1],summary(model3)$Gcov[1])
})

par(mfrow=c(1,2))
hist(cc[1,])   
hist(cc[2,])   
rowMeans(cc)
```


```{r,cache=TRUE}
library(MCMCglmm)
Ainv<-inverseA(bird.families)$Ainv
prior<-list(
	R=list(V=1, nu=0.002), 
	G=list(G1=list(V=1, nu=0.002)))

model2<-MCMCglmm(y~1, 
	random=~taxon, 
	ginverse=list(taxon=Ainv),
	data=dat_x, 
	prior=prior, 
	verbose=FALSE, nitt=13000, burnin=3000, thin=10)
summary(model2)

model3<-MCMCglmm(y~1, 
	random=~taxon, 
	ginverse=list(taxon=Ainv),
	data=dat_y, 
	prior=prior, 
	verbose=FALSE, nitt=13000, burnin=3000, thin=10)
summary(model3)


squid_dat <- simulate_population(
	data_structure=data.frame(taxon=bird.families$tip.label),
	parameters=list(
		taxon=list(
			vcov=1
		),
		residual=list(
			vcov=1
		)
	),
	phylogeny=list(taxon=bird.families),
	n_pop=50
)
lapply(get_population_data(squid_dat,list=TRUE),function(pop_dat){
model2<-MCMCglmm(y~1, 
	random=~taxon, 
	ginverse=list(taxon=Ainv),
	data=pop_dat, 
	prior=prior, 
	verbose=FALSE, nitt=60000, burnin=10000, thin=50)

c(summary(model2)$Gcov[1],summary(model2)$Rcov[1])
})

```


<br><br>



## Ornstein–Uhlenbeck Process
Coming Soon :D

<br><br>
